import array

def sort_data_block(
    signal_data: bytes, partial_records: dict[int, int], record_size: dict[int, int], id_size: int, optional
) -> bytes: ...
def extract(signal_data: bytes, is_byte_array: bool, offsets) -> array.array: ...
def lengths(lst: list[bytes]) -> tuple[int, ...]: ...
def get_vlsd_offsets(lst: list[bytes]) -> tuple[int, ...]: ...
def get_vlsd_max_sample_size(data: bytes, offsets: array.array[int], count: int) -> int: ...
def positions(
    samples: array.array,
    timestamps: array.array,
    plot_samples: array.array,
    plot_timestamps: array.array,
    result: array.array,
    step_obj: int,
    count_obj: int,
    last_obj: int,
    kind: str,
    _size: int,
    itemsize: int,
) -> None: ...
def get_channel_raw_bytes(data_block: bytes, record_size: int, byte_offset: int, byte_count: int) -> bytes: ...
def data_block_from_arrays(data_blocks: list[tuple[array.array, int]], cycles_obj: int) -> bytearray: ...
def get_idx_with_edges(idx: array.array[int]) -> array.array[int]: ...
def reverse_transposition(data: bytes, lines: int, cols: int) -> bytes: ...
def bytes_dtype_size(data: bytes) -> int: ...
