from typing import Any

import numpy as np
from numpy.typing import NDArray

def sort_data_block(
    signal_data: bytes,
    partial_records: dict[int, list[int]],
    record_size: dict[int, int],
    id_size: int,
    optional: object,
) -> bytes: ...
def extract(signal_data: bytes, is_byte_array: int, offsets: NDArray[np.int_]) -> NDArray[np.bytes_]: ...
def lengths(lst: list[bytes]) -> tuple[int, ...]: ...
def get_vlsd_offsets(lst: list[bytes]) -> tuple[int, ...]: ...
def get_vlsd_max_sample_size(data: bytes, offsets: NDArray[np.int_], count: int) -> int: ...
def positions(
    samples: NDArray[Any],
    timestamps: NDArray[Any],
    plot_samples: NDArray[Any],
    plot_timestamps: NDArray[Any],
    result: NDArray[Any],
    step_obj: int,
    count_obj: int,
    last_obj: int,
    kind: str,
    _size: int,
    itemsize: int,
) -> None: ...
def get_channel_raw_bytes(data_block: bytes, record_size: int, byte_offset: int, byte_count: int) -> bytes: ...
def data_block_from_arrays(data_blocks: list[tuple[NDArray, int]], cycles_obj: int) -> bytearray: ...
def get_idx_with_edges(idx: NDArray[np.int_]) -> NDArray[np.int_]: ...
def reverse_transposition(data: bytes, lines: int, cols: int) -> bytes: ...
def bytes_dtype_size(data: bytes) -> int: ...
