def sort_data_block(): ...
def extract(): ...
def lengths(): ...
def get_vlsd_offsets(): ...
def get_vlsd_max_sample_size(): ...
def positions(): ...
def get_channel_raw_bytes(data_block: bytes, record_size: int, byte_offset: int, byte_count: int) -> bytes: ...
def data_block_from_arrays(): ...
def get_idx_with_edges(): ...
def reverse_transposition(): ...
def bytes_dtype_size(): ...
